### ISSUE TITLE
Conduct user interviews and come up with a Persona

### ISSUE THREAD

**Issue by jisie** [nss-day-cohort-24/theme-park-rockin-windows#12]
- [x] Interview at least three parents who have children to understand what kind of experience they would like when they visit a theme park
- [x] come up with a persona.

**Comment by lapinell** [comment]
- Age:
- Gender:
- Income Range:
- Personality:
- Number of kids:
- Hobbies:
- Tech-saaviness:
- How often do you visit amusement parks?
- When do you plan your itinerary for your trip? Do you plan alone or with others? If so, who?
- Walk through your day at an amusement park, from the time you walk in to the time you leave?
- Walk me through your experience waiting in line at a busy amusement park?
- Let's talk about the map:
    - How often do you use maps in general? at a theme park?
     - In what situation do you use maps - in general? at a theme park?
    - Walk us through the steps of using a map - in general? at a theme park?
   - Do you look at a theme park map before the trip? How long before?

**Comment by lapinell** [comment]
- Age: 40
- Gender: female
- Income Range: $40K
- Personality: ENFP-T
- Number of kids: 2 - 12 and 17
- Hobbies: dance, traveling, 
- Tech-saaviness:  7/10
- How often do you visit amusement parks? 2 times per year; with your kids? 1 time per year
- When do you plan your itinerary for your trip? Do you plan alone or with others? If so, who? Doesn't plan; no plans
- Walk through your day at an amusement park, from the time you walk in to the time you leave?
Walk in, look at a map, that looks interesting, lets go, repeat OR these are the spots that we'd like to go to today in that order. Not quite what we thought it would be; the line (too long) or a matter of importance.
- Walk me through your experience waiting in line at a busy amusement park?
There's nothing -- la di da around
- Let's talk about the map:
    - How often do you use maps in general? Yea, all the time.
            - at a theme park? All the time.
     - In what situation do you use maps - in general? 
              - at a theme park? use the key where i want to go and then look at the map to find the most efficient way to get there (time management/efficiency and order of importance)
    - Walk us through the steps of using a map - in general? at a theme park?
   - Do you look at a theme park map before the trip? How long before?

**Comment by marcdledda** [comment]
Age: 59
Gender: Male
Income Range: Middle Class range
Personality: INTJ-A
Number of kids: 3
Hobbies: Slow rides + Shows/Performances
Tech-saaviness: Considers himself techsavy
How often do you visit amusement parks? Once a couple years
When do you plan your itinerary for your trip? Do you plan alone or with others? If so, who?
He plans at the theme park, with the entire family
Walk through your day at an amusement park, from the time you walk in to the time you leave?
-Day at an amusement park:
	"Ride as many rides as he can"
	"Attend a performance/show"
	"Get food"
	"Attend nightshow"
	"Get snacks"
Walk me through your experience waiting in line at a busy amusement park?

Let's talk about the map:
How often do you use maps in general? at a theme park?
In what situation do you use maps - in general? at a theme park?
Walk us through the steps of using a map - in general? at a theme park?
Do you look at a theme park map before the trip? How long before?

**Comment by lapinell** [comment]
- Age: 1963
- Gender: female
- Income Range: $75K
- Personality: Introverted 
- Number of kids: 3 - 28, 29, 31
- Hobbies: Knitting, gardening
- Tech-saaviness: 7/10
- How often do you visit amusement parks? 1-2 per year
- When do you plan your itinerary for your trip? In summer. 
- Do you plan alone or with others? If so, who? Alone and with dad
- Walk through your day at an amusement park, from the time you walk in to the time you leave?
Walk through the gate, ride all the rides, get food, buy souveniers and leave.
- Walk me through your experience waiting in line at a busy amusement park?
OMGod, between the kids and dad - it wasn't that bad. We had fun while we were in line; making fun of everyone else. 
- Let's talk about the map:
    - How often do you use maps in general? at a theme park?
       General: all the time she puts her GPS; at theme park: yea if she has never been there
     - In what situation do you use maps - in general? at a theme park?
     General: to get to point B the quickest; theme park: same 
    - Walk us through the steps of using a map - in general? at a theme park?
     Don't download it on her phone, open it up and read it. 
   - Do you look at a theme park map before the trip? How long before?
      Look at when she gets there.

**Comment by lapinell** [comment]
Persona - Karen Asuncion
**Demographics**
- Age: 40
- Gender: female
- Personality: no one personality stuck out
- Income Range: upper middle class
- Number of kids: 3 - teenagers

**Key Behaviors**
- Tech-saaviness: 8/10
- How often do you visit amusement parks? 2 times per year
- Relaxed-vibe
- no itinerary
- used a map to pin point wanted attractions and bathrooms

**Frustrations & Needs**
- long lines are frustrating
- finding and replacing maps
- keeping track of kids
- child behavior
- other people's behavior
- need food, entertainment, souveniers
- need short lines
- need bathrooms
- need to get to point B quickyl

**Goals**
I want to go to what I know exists and how do I get there quickly and efficiently?


@amberjsharpe
